# Generated by Django 3.1.10 on 2021-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='is_principal',
            field=models.BooleanField(default=False, verbose_name='Is principal?'),
        ),
    ]
